__version__ = '1.0.0'
__version__ = '1.1.1' #Add command /helpop, fix bug in param in command
__version__ = '1.2.0' #Add command /msg, fix bug in command /note (If write group is not found)
__version__ = '1.2.1' #Fix bug in command /я
__version__ = '1.2.2' #Fix bug in _command_starter, rename command /note to /gnote
__version__ = '1.2.3' #Fix bug in command /gnote
__version__ = '1.2.4' #Add func get_command_text, fix bug in command with args
__version__ = '1.2.5' #Fix bug in command /msg
__version__ = '1.2.6' #Fix bug in command /msg (Bug in user_id)
__version__ = '1.2.7' #Fix bug in command /schedule
__version__ = '1.2.8' #Fix bug in command /anote
__version__ = '1.2.9' #Fix bug in command /anote, change functions self_notification
__version__ = '1.2.10' #Fix bug in schedule
__version__ = '1.3.0' #Add command /чат, fix bug in /schedule(Message to long)
